# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hoeg's place
email: peter.steffensen@gmail.com
description:  A Software and Security Engineer writing about cloud, IaC, cyber security, hacking, bug bounty and CTF. 
baseurl: "/"
url: "https://hoeg.github.io"
twitter_username: h033g
github_username:  hoeg

# Build settings
markdown: kramdown
